Map modifications and OutOfBoundsEC
NoVariableGlobal/g.shift pull request #9
Opened 2020-04-10 16:40 UTC by AlejandroPla

2020-04-10 17:15 UTC, GonzaPM7 approved these changes

2020-04-17 19:16 UTC, pablojor approved these changes

2020-04-17 20:23 UTC, kyranet requested changes

2020-04-17 20:23 UTC, kyranet commented on src/OutOfBoundsEC.cpp
> +    TransformComponent* transform = dynamic_cast<TransformComponent*>(
```suggestion
    TransformComponent* transform = reinterpret_cast<TransformComponent*>(
```

2020-04-17 22:33 UTC, kyranet approved these changes

2020-04-17 22:33 UTC, merged